In [28]:
import pandas as pd
from sqlalchemy import create_engine, text
import pyodbc as odbc
import json

connection_parameters = '''{
"andromeda" : 
    "DRIVER={ODBC Driver 17 for SQL Server};    SERVER=andromeda;    DATABASE=MIS_RIESGOS;    Trusted_Connection=yes;"
}'''
connection_string = json.loads(connection_parameters)['andromeda']
engine = create_engine('mssql+pyodbc:///?odbc_connect='+ connection_string)

with engine.connect() as conn:
    df = pd.read_sql_query('select getdate() as fecha_actual', con=conn)

df.head()

             fecha_actual
0 2026-04-28 11:39:44.500

In [ ]:
import pandas as pd
import pyodbc as odbc
import json

connection_string = '''{
"andromeda" : 
    "DRIVER={ODBC Driver 17 for SQL Server};    SERVER=andromeda;    DATABASE=MIS_RIESGOS;    Trusted_Connection=yes;"
}'''
connection_string = json.loads(connection_string)['andromeda']

connex = odbc.connect(connection_string)
df = pd.read_sql_query('select getdate() as fecha', con=connex)
connex.close()
df.head()

C:\Users\HN34064\AppData\Local\Temp\ipykernel_18044\3308858932.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select getdate() as fecha', con=connex)

                    fecha
0 2026-04-28 11:35:11.477

In [ ]:
import pyodbc as odbc
import json

connection_string = '''{
"andromeda" : 
    "DRIVER={ODBC Driver 17 for SQL Server};    SERVER=andromeda;    DATABASE=MIS_RIESGOS;    Trusted_Connection=yes;"
}'''
connection_string = json.loads(connection_string)['andromeda']

connection = odbc.connect(connection_string)
cursor = connection.cursor()
ob = cursor.execute('select getdate() as fecha_actual')
ob = ob.fetchall()[0]
ob[0]

In [ ]:
connex.close()

ProgrammingError: Attempt to use a closed connection.

:

In [66]:
import sqlite3

con = sqlite3.connect('nueva_base')
cursor = con.cursor()
ob = cursor.execute('select current_date as fecha')
ob.fetchall()

[('2026-04-28',)]